#!/bin/bash

pandoc -s -t man vscpl2drv-websocksrv.1.md -o vscpl2drv-websocksrv.1
tar -zcvf vscpl2drv-websocksrv.1.gz vscpl2drv-websocksrv.1
sudo cp vscpl2drv-websocksrv.1.gz /usr/share/man/man1/
mandb
